import Head from "next/head";
import React, { FC, useEffect } from "react";
import Navbar from "./navbar";

type LayoutProps = {
	title?: string;
	disableContainer?: true;
};

const Layout: FC<LayoutProps> = ({
	children,
	title = "MadSoft",
	disableContainer = false,
}) => {
	useEffect(() => {
		(async () => {
			const M = await import("materialize-css");
			M.AutoInit();
		})();
	}, []);
	return (
		<>
			<Head>
				<title>{title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<meta name="description" content="MadSoft - stránky Michala Maděry. Věnuji se počítačům a programování. Na těchto stránkách je seznam mých projektů." />
				<meta name="keywords" content="programování, programming, personal page" />
  				<meta name="author" content="Michal Maděra" />
			</Head>
			<main>
				<Navbar />
				<div className={disableContainer ? "" : "container"}>{children}</div>
			</main>
		</>
	);
};

export default Layout;
