import Head from "next/head";
import Script from "next/script";
import React, { FC, useEffect } from "react";
import Navbar from "./navbar";

type LayoutProps = {
	title?: string;
};

const Layout: FC<LayoutProps> = ({ children, title = "MadSoft" }) => {
	useEffect(() => {
		(async () => {
			const M = await import("materialize-css");
			M.AutoInit();
		})();
	}, []);
	return (
		<>
			<Head>
				<title>{title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Navbar />
				{children}
				{/* <Script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js" /> */}
			</main>
		</>
	)
;};

export default Layout;
